# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.IntegerField(verbose_name='市区町村ID')),
                ('pref_id', models.IntegerField(verbose_name='都道府県ID')),
                ('city_part_id', models.IntegerField(verbose_name='市区町村PartID')),
                ('name', models.CharField(max_length=255, verbose_name='市区町村名')),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='緯度')),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='経度')),
            ],
        ),
        migrations.CreateModel(
            name='DartsNearStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.IntegerField(verbose_name='駅ID')),
                ('shop_id', models.IntegerField(verbose_name='店舗ID')),
                ('walk_time', models.IntegerField(verbose_name='徒歩時間')),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.IntegerField(verbose_name='路線ID')),
                ('name', models.CharField(max_length=255, verbose_name='路線名')),
            ],
        ),
        migrations.CreateModel(
            name='LineStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.IntegerField(verbose_name='路線ID')),
                ('station_id', models.IntegerField(verbose_name='駅ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref_id', models.IntegerField(verbose_name='都道府県ID')),
                ('name', models.CharField(max_length=255, verbose_name='都道府県名')),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='緯度')),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='経度')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.IntegerField(verbose_name='店舗ID')),
                ('name', models.CharField(max_length=255, verbose_name='店名')),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='緯度')),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='経度')),
                ('holiday', models.CharField(max_length=255, verbose_name='定休日')),
                ('time', models.CharField(max_length=255, verbose_name='営業時間')),
                ('address', models.CharField(max_length=255, verbose_name='住所')),
                ('information', models.TextField(verbose_name='店舗情報')),
                ('dartslive', models.IntegerField(blank=True, default=0, verbose_name='DARTSLIVE2')),
                ('phoenix', models.IntegerField(blank=True, default=0, verbose_name='PHOENIX')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('tel', models.CharField(max_length=255, verbose_name='TEL')),
                ('station', models.CharField(max_length=255, verbose_name='最寄駅')),
                ('pref_id', models.IntegerField(verbose_name='都道府県ID')),
                ('city_id', models.IntegerField(verbose_name='市区町村ID')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.IntegerField(verbose_name='駅ID')),
                ('pref_id', models.IntegerField(verbose_name='都道府県ID')),
                ('city_id', models.IntegerField(verbose_name='市区町村ID')),
                ('name', models.CharField(max_length=255, verbose_name='都道府県名')),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='緯度')),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='経度')),
            ],
        ),
    ]
