# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Darts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='書籍名')),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='緯度')),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='経度')),
                ('holiday', models.CharField(max_length=255, verbose_name='定休日')),
                ('time', models.CharField(max_length=255, verbose_name='営業時間')),
                ('address', models.CharField(max_length=255, verbose_name='住所')),
                ('information', models.TextField(verbose_name='店舗情報')),
                ('dartslive', models.IntegerField(blank=True, default=0, verbose_name='DARTSLIVE2')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('tel', models.CharField(max_length=255, verbose_name='TEL')),
                ('station', models.CharField(max_length=255, verbose_name='最寄駅')),
            ],
        ),
    ]
