# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='shop_id',
        ),
    ]
