# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.IntegerField(verbose_name='市区町村ID')),
                ('pref_id', models.IntegerField(verbose_name='都道府県ID')),
                ('city_part_id', models.IntegerField(verbose_name='市区町村PartID')),
                ('name', models.CharField(max_length=255, verbose_name='市区町村名')),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='緯度')),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='経度')),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.IntegerField(verbose_name='路線ID')),
                ('name', models.CharField(max_length=255, verbose_name='路線名')),
            ],
        ),
        migrations.CreateModel(
            name='LineStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.IntegerField(verbose_name='路線ID')),
                ('station_id', models.IntegerField(verbose_name='駅ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref_id', models.IntegerField(verbose_name='都道府県ID')),
                ('name', models.CharField(max_length=255, verbose_name='都道府県名')),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='緯度')),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='経度')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.IntegerField(verbose_name='駅ID')),
                ('pref_id', models.IntegerField(verbose_name='都道府県ID')),
                ('city_id', models.IntegerField(verbose_name='市区町村ID')),
                ('name', models.CharField(max_length=255, verbose_name='都道府県名')),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='緯度')),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='経度')),
            ],
        ),
    ]
